name: Format Code python

on:
  push:
    branches: [ master ]

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Check formatting
      run: |
        black --check .

  format-code:
    needs: check-formatting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Format code
      run: |
        black .
        
    - name: Commit formatted code
      run: |
        git config --global user.email "${{ secrets.USER_EMAIL }}"
        git config --global user.name "${{ secrets.USER_NAME }}"
        git add -u
        git diff-index --quiet HEAD || git commit -m "Auto-format code"
        git push
